services:
  db:
    image: postgis/postgis:15-3.3
    container_name: medigo_db
    environment:
      POSTGRES_USER: medigo_user
      POSTGRES_PASSWORD: medigo_password
      POSTGRES_DB: medigo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
